### ISSUE TITLE
soooooo dope

### ISSUE THREAD

**Issue by joshuawootonn** [tedpaulsen/mac-setup#1]

**Comment by joshuawootonn** [comment]
Isn't this what gists are for????

**Comment by joshuawootonn** [comment]
![](https://media.giphy.com/media/3sbZaElzV2J8ZVsSYg/giphy.gif)

**Comment by joshuawootonn** [comment]
dude I love you :)

**Comment by tedpaulsen** [comment]
this is a duplicate of #2 closing
